version: '3.8'
services:
  python-app:
    build: .
    container_name: python-app
    ports:
      - 80:8000
    depends_on: 
      - db 

  db:
    image: postgres:16.3-alpine3.20
    container_name: db
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  default:
    driver: host

volumes:
  db:
