name: composite action

runs:
  upload:
    using: 'composite'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: ./.github/workflows/test_on_push.yml

      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./Dockerfile
            ./docker-compose.yml
            ./main.py
            ./requirements.txt
          outPath: src.tar.gz

      - name: Upload to ftp server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 37.143.8.66
          username: my
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            [!src.tar.gz]