name: Run tests on any Push event
on:
  push:
    branches:
      - 'releases/**'
      - 'feature/**'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: composite
        uses: ./.github/actions/setup-composite