name: Run tests on any Push event
on:
  push:
    branches:
      - 'releases/*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v1
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run a Docker container
        run: docker compose up -d

      - name: Run tests
        run: python3 tests.py
