name: Run tests on master pull request
on:
  push:
    branches:
      - 'releases/**'
      - 'feature/**'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: composite
        secrets: |
          "ftp_password: ${{ secrets.FTP_PASSWORD }}"
        uses: ./.github/actions/setup-composite
        with:
          ftp_password