name: Run tests on master pull request
on:
  push:
    branches:
      - 'releases/**'
      - 'feature/**'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: composite
        uses: ./.github/actions/setup-composite